### ISSUE TITLE
Passing in unknown option shows a bad error

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/mutant-chicken#17]
When an unknown option is passed we currently show an error message. We should improve this. I've given some examples of how `dotnet` handles this.

```
c:\Data\mycode\mutant-chicken>dotnet new3 source --unknownoption
Unrecognized option '--unknownoption'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at dotnet_new3.Program.Main(String[] args) in c:\Data\mycode\mutant-chicken\src\dotnet-new3\Program.cs:line 59
```

Compare this to passing a bad option to `dotnet`.

```
>dotnet restore --unknown
Specify --help for a list of available options and commands.
error: Unrecognized option '--unknown'
```

```
>dotnet --unknownffff
Unknown option: --unknownffff
.NET Command Line Tools (1.0.0-rc2-002543)
Usage: dotnet [common-options] [command] [arguments]

Arguments:
  [command]     The command to execute
  [arguments]   Arguments to pass to the command

Common Options (passed before the command):
  -v|--verbose  Enable verbose output
  --version     Display .NET CLI Version Number
  --info        Display .NET CLI Info

Common Commands:
  new           Initialize a basic .NET project
  restore       Restore dependencies specified in the .NET project
  build         Builds a .NET project
  publish       Publishes a .NET project for deployment (including the runtime)
  run           Compiles and immediately executes a .NET project
  test          Runs unit tests using the test runner specified in the project
  pack          Creates a NuGet package
```

**Comment by mlorbetske** [comment]
Looks like this is blocked by https://github.com/dotnet/cli/issues/2728

**Comment by mlorbetske** [comment]
The only nested command remaining is reset (which will be replaced with `dotnet new3 -u *`) so this shouldn't be an issue anymore.

Non-baked in switches are the way that parameters are passed to templates, so `dotnet new3 mvc -n test -d --message foo` would set the value `foo` to a parameter called `message` defined in the template manifest (not by `dotnet new3`)
