### ISSUE TITLE
Passing --help for source shows an error

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/mutant-chicken#18]
```
>dotnet new3 source --help
Unrecognized option '--help'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at dotnet_new3.Program.Main(String[] args) in c:\Data\mycode\mutant-chicken\src\dotnet-new3\Program.cs:line 59
```

Also related add --remove or --uninstall to the --install item

**Comment by mlorbetske** [comment]
This is interesting - it looks like it works if you do `dotnet new3 --help source`, after adding the help option to the source command, but putting `--help` at the end still throws

**Comment by mlorbetske** [comment]
Looks like this is blocked by dotnet/cli#2728

**Comment by mlorbetske** [comment]
There are no nested commands anymore and `-h|--help` works at the root
