### ISSUE TITLE
Improve help for source

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/mutant-chicken#30]
We should improve the help experience for the source command.

```
C:\temp\dn3\WebAppFromVs\from-dn3>dotnet new3 source --help
Unrecognized option '--help'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at dotnet_new3.Program.Main(String[] args) in c:\Data\mycode\mutant-chicken\src\dotnet-new3\Program.cs:line 59

C:\temp\dn3\WebAppFromVs\from-dn3>dotnet new3 source add --help
Unrecognized option '--help'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at dotnet_new3.Program.Main(String[] args) in c:\Data\mycode\mutant-chicken\src\dotnet-new3\Program.cs:line 59
```

**Comment by mlorbetske** [comment]
Dup of #18 `dotnet new3 --help source` and `dotnet new3 --help source add` are the way this is expected to work per https://github.com/dotnet/cli/issues/2728

**Comment by sayedihashimi** [comment]
@mlorbetske OK, let's follow on the general issue at #18. We will bring it up after the demo.

Iin this case I tried `dotnet new3 --help source remove` based on your comment and I expected it to work.

```
dotnet new3 --help source remove
Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at dotnet_new3.Broker.RemoveConfiguredSource(String alias) in c:\Data\mycode\mutant-chicken\src\dotnet-new3\Broker.cs:line 122
   at dotnet_new3.RemoveSourceCommand.<>c__DisplayClass0_0.<Configure>b__0() in c:\Data\mycode\mutant-chicken\src\dotnet-new3\RemoveSourceCommand.cs:line 14
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at dotnet_new3.Program.Main(String[] args) in c:\Data\mycode\mutant-chicken\src\dotnet-new3\Program.cs:line 59
```

**Comment by sayedihashimi** [comment]
Reopending for now to track the error with `dotnet new3 --help source remove`

**Comment by mlorbetske** [comment]
@sayedihashimi let's close this and add --remove or --uninstall to the --install item, since these will both be top level options, -h/--help will work and circumvent the cli bug

**Comment by sayedihashimi** [comment]
OK
